file(READ "${INPUT}" _spv HEX)
string(LENGTH "${_spv}" _hex_len)
math(EXPR _word_count "${_hex_len} / 8")
set(_out "#pragma once\n#include <stdint.h>\nstatic const uint32_t ${SYMBOL}[] = {\n")
set(_i 0)
while(_i LESS _word_count)
    math(EXPR _p "${_i} * 8")
    string(SUBSTRING "${_spv}" ${_p} 8 _hex)
    string(SUBSTRING "${_hex}" 0 2 _b0)
    string(SUBSTRING "${_hex}" 2 2 _b1)
    string(SUBSTRING "${_hex}" 4 2 _b2)
    string(SUBSTRING "${_hex}" 6 2 _b3)
    string(APPEND _out "0x${_b3}${_b2}${_b1}${_b0}u,")
    math(EXPR _mod "${_i} % 8")
    if(_mod EQUAL 7)
        string(APPEND _out "\n")
    endif()
    math(EXPR _i "${_i} + 1")
endwhile()
string(APPEND _out "\n};\nstatic const uint32_t ${SYMBOL}_word_count = ${_word_count}u;\n")
file(WRITE "${OUTPUT}" "${_out}")
