#!/usr/bin/env bash
# setup_game.sh — Bootstrap a new PSX game for psxrecomp.
#
# Usage:
#   ./setup_game.sh <game_name> <bin_path> <cue_path> [exe_output_name] [game_id_override]
#
# Example:
#   ./setup_game.sh "Game Name" "path/to/bin" \
#                                    "path/to/cue"
#
# What this does:
#   1. Extracts the PS-X EXE from the disc image via tools/extract_psx_exe.py
#   2. Creates seeds/<game>/seeds.txt
#   3. Generates game-<game>.toml with the extracted EXE metadata
#   4. Auto-patches runtime/CMakeLists.txt (inserts the game target before if(BUILD_TESTING))
#   5. Creates build_<game>.sh, recomp_<game>.sh, run_<game>.sh helper scripts
#   6. Runs the recompiler to generate C code
#
# Prerequisites:
#   - Python 3 on PATH
#   - tools/extract_psx_exe.py present
#   - The disc .bin and .cue files must exist
#   - The recompiler must have been built (./build_recompiler.sh)

set -euo pipefail

if [ $# -lt 3 ]; then
    echo "Usage: $0 <game_name> <bin_path> <cue_path> [exe_output_name] [game_id_override]"
    echo "Example: $0 \"Game Name\" \"path/to/bin\" \\"
    echo "                              \"path/to/cue\""
    exit 1
fi

GAME_NAME="$1"
BIN_PATH="$2"
CUE_PATH="$3"
EXE_OUTPUT="${4:-}"
GAME_ID_OVERRIDE="${5:-}"

# Derive a filesystem-safe slug from the game name
SLUG=$(echo "$GAME_NAME" | tr '[:upper:]' '[:lower:]' | tr -cd 'a-z0-9 _-' | tr ' ' '_' | tr -cd 'a-z0-9_-' | sed 's/_*$//')

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$SCRIPT_DIR"

# ---- Prerequisite checks ----
if [ ! -f "$REPO_ROOT/tools/extract_psx_exe.py" ]; then
    echo "ERROR: tools/extract_psx_exe.py not found. Is this a psxrecomp repo?"
    exit 1
fi
if [ ! -f "$BIN_PATH" ]; then
    echo "ERROR: disc bin not found: $BIN_PATH"
    exit 1
fi
if [ ! -f "$CUE_PATH" ]; then
    echo "ERROR: disc cue not found: $CUE_PATH"
    exit 1
fi

# ---- Step 1: Extract PS-X EXE ----
echo ""
echo "=== Step 1: Extracting PS-X EXE from disc ==="

EXE_OUT_DIR=$(dirname "$BIN_PATH")
if [ -z "$EXE_OUTPUT" ]; then
    EXE_OUTPUT="${EXE_OUT_DIR}/${SLUG}.exe"
fi

EXTRACT_OUTPUT=$(python3 "$REPO_ROOT/tools/extract_psx_exe.py" "$BIN_PATH" "$EXE_OUTPUT" 2>&1)
echo "$EXTRACT_OUTPUT"

# ---- Step 2: Parse EXE metadata ----
echo ""
echo "=== Step 2: Parsing EXE metadata ==="

LOAD_ADDR=$(echo "$EXTRACT_OUTPUT" | grep "Load addr:" | head -1 | sed 's/.*Load addr:\s*//' | tr -d '\r' | xargs)
ENTRY_PC=$(echo "$EXTRACT_OUTPUT" | grep "Initial PC:" | head -1 | sed 's/.*Initial PC:\s*//' | tr -d '\r' | xargs)
FILE_SIZE_DEC=$(echo "$EXTRACT_OUTPUT" | grep "File size:" | head -1 | sed 's/.*File size:\s*//' | tr -d '\r' | awk '{print $1}')
FILE_SIZE_HEX=$(printf "0x%08X" "$FILE_SIZE_DEC")

# Determine game ID
GAME_ID=""
if [ -n "$GAME_ID_OVERRIDE" ]; then
    GAME_ID="$GAME_ID_OVERRIDE"
else
    GAME_ID=$(echo "$EXTRACT_OUTPUT" | grep "Game ID (from SYSTEM.CNF" | head -1 | sed 's/.*Game ID.*:\s*//' | tr -d '\r' | xargs | sed 's/;1$//')
    if [ -z "$GAME_ID" ]; then
        GAME_ID=$(echo "$EXTRACT_OUTPUT" | grep '^\s*id\s*=' | head -1 | sed 's/.*id\s*=\s*"\(.*\)"/\1/' | tr -d '\r' | xargs)
    fi
fi
if [ -z "$GAME_ID" ]; then
    GAME_ID="UNKNOWN"
fi

# Determine stack base
STACK_BASE=$(echo "$EXTRACT_OUTPUT" | grep "STACK =" | head -1 | sed 's/.*STACK\s*=\s*//' | tr -d '\r' | xargs)
if [ -z "$STACK_BASE" ]; then
    STACK_BASE="801FFF00"
fi
STACK_BASE="0x${STACK_BASE}"

# Determine disc region from the EXE header region field
REGION=$(echo "$EXTRACT_OUTPUT" | grep "Region:" | head -1 | sed 's/.*Region:\s*//' | tr -d '\r' | xargs)
case "$REGION" in
    a|A)  REGION_LABEL="NTSC-U" ;;
    e|E)  REGION_LABEL="PAL" ;;
    j|J)  REGION_LABEL="NTSC-J" ;;
    *)    REGION_LABEL="$REGION" ;;
esac

echo "  Game Name:   $GAME_NAME"
echo "  Slug:        $SLUG"
echo "  Game ID:     $GAME_ID"
echo "  Load Addr:   $LOAD_ADDR"
echo "  Entry PC:    $ENTRY_PC"
echo "  File Size:   $FILE_SIZE_HEX ($FILE_SIZE_DEC bytes)"
echo "  Stack Base:  $STACK_BASE"
echo "  Region:      $REGION ($REGION_LABEL)"
echo "  EXE Output:  $EXE_OUTPUT"

# ---- Step 3: Create seeds directory ----
echo ""
echo "=== Step 3: Creating seeds ==="
mkdir -p "$REPO_ROOT/seeds/$SLUG"
cat > "$REPO_ROOT/seeds/$SLUG/seeds.txt" << SEEDEOF
# ${GAME_NAME} (${GAME_ID}) function seeds
# Generated by whole-image discovery.
# Format: <address> <name>   (one per line)
SEEDEOF
echo "  Created seeds/$SLUG/seeds.txt"

# ---- Step 4: Generate game config (game-<slug>.toml) ----
echo ""
echo "=== Step 4: Generating game config ==="

PORT_HASH=$(echo "$SLUG" | cksum | awk '{print $1}')
DEBUG_PORT=$(( 4373 + (PORT_HASH % 100) ))
WINDOW_TITLE="psxrecomp - ${GAME_NAME}"
CONFIG_FILE="game-${SLUG}.toml"

cat > "$REPO_ROOT/$CONFIG_FILE" << TOMLEOF
# ${GAME_NAME} (${GAME_ID}) — PSXRecomp game configuration
[game]
name          = "${GAME_NAME}"
id            = "${GAME_ID}"
exe           = "${EXE_OUTPUT}"
load_address  = "${LOAD_ADDR}"
entry_pc      = "${ENTRY_PC}"
text_size     = "${FILE_SIZE_HEX}"
stack_base    = "${STACK_BASE}"
disc          = "${CUE_PATH}"

[recompiler]
seeds     = "seeds/${SLUG}/seeds.txt"
out_dir   = "generated/${SLUG}"
strict    = true
discovery = "whole-image"

[runtime]
debug_port    = ${DEBUG_PORT}
window_title  = "${WINDOW_TITLE}"
controller    = "digital"
memcard_dir   = "."

[video]
aspect_ratio = "4:3"
TOMLEOF
echo "  Created ${CONFIG_FILE}"

# ---- Step 5: Create helper scripts ----
echo ""
echo "=== Step 5: Creating helper scripts ==="

EXE_BASENAME_NOEXT="${EXE_OUTPUT##*/}"
EXE_BASENAME_NOEXT="${EXE_BASENAME_NOEXT%.*}"

# Recomp script
cat > "$REPO_ROOT/recomp_${SLUG}.sh" << RECOMPEOF
#!/usr/bin/env bash
# Regenerate the ${GAME_NAME} C code from the extracted PS-X EXE.
# Prerequisites: build the recompiler first (./build_recompiler.sh).
set -euo pipefail
cd "\$(dirname "\$0")"
recompiler/build/psxrecomp-game --config ${CONFIG_FILE}
RECOMPEOF
chmod +x "$REPO_ROOT/recomp_${SLUG}.sh"

# Build script
cat > "$REPO_ROOT/build_${SLUG}.sh" << BUILDEOF
#!/usr/bin/env bash
# Build the ${GAME_NAME} runtime target.
# Prerequisites: build the recompiler first (./build_recompiler.sh),
# then generate game C code (./recomp_${SLUG}.sh).
set -euo pipefail
cd "\$(dirname "\$0")"
cmake -S runtime -B runtime/build -G Ninja -DCMAKE_BUILD_TYPE=Release
cmake --build runtime/build --target psx-${SLUG}
BUILDEOF
chmod +x "$REPO_ROOT/build_${SLUG}.sh"

# Run script
TARGET_BASENAME="psxrecomp___${GAME_NAME// /_}"
cat > "$REPO_ROOT/run_${SLUG}.sh" << RUNEOF
#!/usr/bin/env bash
# Run the ${GAME_NAME} recompiled binary.
set -euo pipefail
cd "\$(dirname "\$0")"
./runtime/build/${TARGET_BASENAME} --game ${CONFIG_FILE} --disc "${CUE_PATH}"
RUNEOF
chmod +x "$REPO_ROOT/run_${SLUG}.sh"

echo "  Created recomp_${SLUG}.sh"
echo "  Created build_${SLUG}.sh"
echo "  Created run_${SLUG}.sh"

# ---- Step 6: Auto-patch runtime/CMakeLists.txt ----
echo ""
echo "=== Step 6: Patching runtime/CMakeLists.txt ==="

CMAKE_FILE="$REPO_ROOT/runtime/CMakeLists.txt"
CMAKE_TARGET="psx-${SLUG}"
CMAKE_VAR_PREFIX=$(echo "${SLUG^^}_GENERATED_FULL_C" | tr '.-' '__')

# Build the CMake block as a Python string to avoid shell escaping hell
PYTHON_PATCH=$(cat << PYEOF
import sys, os

cmake_file = sys.argv[1]
cmake_target = sys.argv[2]
cmake_block = sys.argv[3]

with open(cmake_file, 'r') as f:
    content = f.read()

# Check if target already exists
if f"psxrecomp_add_runtime_target({cmake_target}" in content:
    print(f"  Target {cmake_target} already exists — skipping patch.")
    sys.exit(0)

# Insert before if(BUILD_TESTING)
anchor = "if(BUILD_TESTING)"
if anchor in content:
    idx = content.find(anchor)
    new_content = content[:idx] + cmake_block + "\n" + content[idx:]
    with open(cmake_file, 'w') as f:
        f.write(new_content)
    print(f"  ✓ Inserted {cmake_target} target before {anchor}")
else:
    print(f"  WARNING: Could not find '{anchor}' anchor in CMakeLists.txt.")
    print(f"  Manual insertion required.")
    sys.exit(1)
PYEOF
)

# Build the CMake block to insert
CMAKE_BLOCK=$(cat << CMAKEOF

# ---- ${GAME_NAME} game target --------------------------------------------------
# Build with: cmake --build runtime/build --target ${CMAKE_TARGET}

file(GLOB ${CMAKE_VAR_PREFIX}
    "\${PSXRECOMP_ROOT}/generated/${SLUG}/${EXE_BASENAME_NOEXT}_full_*.c"
)

psxrecomp_add_runtime_target(${CMAKE_TARGET}
    DEBUG_PORT ${DEBUG_PORT}
    WINDOW_TITLE "${WINDOW_TITLE}"
    DEFAULT_GAME_CONFIG_PATH "${CONFIG_FILE}"
    GAME_GENERATED_DISPATCH_C "\${PSXRECOMP_ROOT}/generated/${SLUG}/${EXE_BASENAME_NOEXT}_dispatch.c"
    GAME_GENERATED_FULL_C \${${CMAKE_VAR_PREFIX}}
)
CMAKEOF
)

python3 -c "$PYTHON_PATCH" "$CMAKE_FILE" "$CMAKE_TARGET" "$CMAKE_BLOCK"

# ---- Step 7: Run recompiler ----
echo ""
echo "=== Step 7: Running recompiler ==="

if [ -x "$REPO_ROOT/recompiler/build/psxrecomp-game" ]; then
    echo "  Running psxrecomp-game --config ${CONFIG_FILE} ..."
    cd "$REPO_ROOT"
    "$REPO_ROOT/recompiler/build/psxrecomp-game" --config "$CONFIG_FILE" 2>&1 | tail -5
    echo "  ✓ Recompilation complete"
else
    echo "  WARNING: psxrecomp-game not found at recompiler/build/psxrecomp-game."
    echo "  Build the recompiler first: ./build_recompiler.sh"
    echo "  Then run:                   ./recomp_${SLUG}.sh"
fi

# ---- Done ----
echo ""
echo "========================================"
echo "  Setup complete for ${GAME_NAME}"
echo "========================================"
echo ""
echo "  Next steps:"
echo "    1. Build runtime:  ./build_${SLUG}.sh"
echo "    2. Play:           ./run_${SLUG}.sh"
echo ""
