# hash_codegen.cmake — generate overlay_codegen_hash.h with a content hash of the
# recompiler's codegen sources, so the overlay cache path (gcc/<arch-abi>/cg<N>_<hash>/)
# changes automatically whenever the emitter changes. This closes the gap where a
# pure-emitter change within the same manual PSX_OVERLAY_CODEGEN_VER produced a
# different DLL the cache happily reused (a stale-but-cgN load — the v0.3.0 black
# screen). Both the runtime loader (via overlay_api.h) and compile_overlays.py read
# the generated PSX_OVERLAY_CODEGEN_HASH, so the two sides never drift.
#
# Invoked as: cmake -DOUT=<header> -DROOT=<repo> "-DSRCS=<a>;<b>;..."
#             -P hash_codegen.cmake
# Re-runs whenever a listed source changes (it's an add_custom_command DEPENDS).

if(NOT DEFINED OUT OR OUT STREQUAL "")
    message(FATAL_ERROR "hash_codegen.cmake requires a non-empty OUT")
endif()
if(NOT DEFINED ROOT OR ROOT STREQUAL "")
    message(FATAL_ERROR "hash_codegen.cmake requires a non-empty ROOT")
endif()
if(NOT IS_DIRECTORY "${ROOT}")
    message(FATAL_ERROR "hash_codegen.cmake ROOT is not a directory: ${ROOT}")
endif()
if(NOT DEFINED SRCS OR SRCS STREQUAL "")
    message(FATAL_ERROR "hash_codegen.cmake requires at least one source in SRCS")
endif()

file(REAL_PATH "${ROOT}" _root)
set(_records "")
foreach(f IN LISTS SRCS)
    if(f STREQUAL "")
        message(FATAL_ERROR "hash_codegen.cmake SRCS contains an empty path")
    endif()
    if(NOT EXISTS "${f}" OR IS_DIRECTORY "${f}")
        message(FATAL_ERROR "hash_codegen.cmake source is missing or not a file: ${f}")
    endif()

    file(SIZE "${f}" _size)
    if(_size EQUAL 0)
        message(FATAL_ERROR "hash_codegen.cmake source is empty: ${f}")
    endif()

    file(REAL_PATH "${f}" _real)
    file(RELATIVE_PATH _rel "${_root}" "${_real}")
    string(REPLACE "\\" "/" _rel "${_rel}")
    if(_rel STREQUAL ".." OR _rel MATCHES "^\\.\\./")
        message(FATAL_ERROR "hash_codegen.cmake source is outside ROOT: ${f}")
    endif()

    file(SHA256 "${_real}" _digest)
    string(LENGTH "${_rel}" _rel_len)
    # Length-prefix the stable repo-relative path and fixed-size content digest.
    # This keeps the hash independent of checkout location and prevents adjacent
    # file contents from producing the same byte stream at different boundaries.
    string(APPEND _records "path:${_rel_len}:${_rel}\nsha256:64:${_digest}\n")
endforeach()
string(SHA256 _h "${_records}")
string(SUBSTRING "${_h}" 0 8 _h8)

set(_content "/* AUTO-GENERATED by hash_codegen.cmake — do not edit, do not commit.
 * Content hash of the recompiler codegen sources; folded into the overlay cache
 * path so an emitter change never reuses a stale DLL. */
#pragma once
#define PSX_OVERLAY_CODEGEN_HASH 0x${_h8}u
")

# Only rewrite when the value actually changes, so dependents don't rebuild on
# every invocation.
if(EXISTS "${OUT}")
    file(READ "${OUT}" _old)
    if(_old STREQUAL _content)
        return()
    endif()
endif()
file(WRITE "${OUT}" "${_content}")
message(STATUS "overlay codegen hash: 0x${_h8}")
